export const RIM = 1
export const GRASSLAND = 2
export const MARBLE = 3
export const SCRATCHED = 4
export const ENTRANCE = 5
export const WALL = 6
export const FLOOR = 7
export const EXIT = 8
export const TREASURE = 9
export const COLLISION_TILES = [RIM, WALL]
