export const RIM = 1
export const GRASSLAND = 2
export const MARBLE = 3
export const SCRATCHED = 4
export const ENTRANCE = 5
export const WALL = 6
export const FLOOR = 7
export const EXIT = 8
export const TREASURE = 9
export const POND = 10
export const COLLISION_TILES = [RIM, WALL, POND]

export const BACK_0 = 1
export const BACK_1 = 0
export const BACK_2 = 2
export const RIGHT_0 = 4
export const RIGHT_1 = 3
export const RIGHT_2 = 5
export const FRONT_0 = 7
export const FRONT_1 = 6
export const FRONT_2 = 8
export const LEFT_0 = 10
export const LEFT_1 = 9
export const LEFT_2 = 11
